# dbt_project.yml - Main dbt configuration

name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

profile: 'ecommerce'

# Project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  ecommerce_analytics:
    # Staging models
    staging:
      +materialized: view
      +schema: staging
    
    # Intermediate models
    intermediate:
      +materialized: ephemeral
    
    # Mart models
    marts:
      +materialized: table
      +schema: marts

# Variables
vars:
  start_date: '2023-01-01'
  default_country: 'USA'